### ISSUE TITLE
"Quantifiers support is disabled"

### ISSUE THREAD

**Issue by chloesack92** [bitwuzla/bitwuzla#7]
Today I tried using bitwuzla_mk_var and BITWUZLA_KIND_EXISTS for the first time, in the context of some simple FP expressions.

When I tried to run bitwuzla, it said:

`[bzlacore] bzla_check_sat: Quantifiers support is disabled.`

changing BITWUZLA_OPT_ENGINE to "quant" didn't seem to help.

So, I am wondering, how can I enable quantifiers support?

**Comment by mpreiner** [comment]
Hi @chloesack92, Bitwuzla originally only supported quantifiers with bit-vectors. We are currently refactoring the quantifier engine to handle quantifiers in combination with all theories supported by Bitwuzla. The old code had several issues that we won't fix anymore since the code will be obsolete. Instead we decided to disable the support until the refactor is done.

**Comment by chloesack92** [comment]
Hi @mpreiner :smile: That makes sense. Do you know roughly when the refactor will be done - is it a few weeks away, or do you think it will be much longer?

**Comment by mpreiner** [comment]
Unfortunately, we won't be able to finish the refactor within the next few weeks. We plan to have a first working version by the end of March 2022. If we manage to finish earlier, we'll let you know.

**Comment by chloesack92** [comment]
I understand, and that is very helpful to know. Thank you. :)
